name: linux

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://maciejpatro/ubuntu-20.04-gcc-10
      - name: Test with pytest
        run: |
          cmake -v
          ninja -v
